server:
  port: 8083

i2:
  keycloak:
    auth-server-url: http://localhost:8080/auth #
    realm: master
    username: admin #
    password: admin #
    client-id: admin-cli
  init:
    realm:
      name: test #
    smtp:
      host: me-email
      port: 1025
      from: noreply@smartb.city
      ssl: false
      starttls: false
      auth: false
    admin-client:
      id: i2-api
      roles: # assign client roles to the user
        client-id: realm-management
        roles:
          - create-client
          - manage-clients
          - manage-users
          - view-clients
          - view-users
    admin-user:
      username: admin #
      email: admin@admin.com #
      firstname: admin #
      lastname: admin #
      role: # assign a client role to the user
        name: realm-admin
        client-id: realm-management
