server:
  port: 8083

i2:
  keycloak:
    auth-server-url: http://localhost:8080/auth
    realm: master
    username: admin
    password: admin
    client-id: admin-cli
  init:
    realm: test
    smtp:
      host: me-email
      port: 1025
      from: noreply@smartb.city
      ssl: false
      starttls: false
      auth: false
    admin-client: i2-api
    admin-user:
      username: admin
      email: admin@admin.com
      firstname: admin
      lastname: admin
    base-roles:
      - super_admin
      - im_read_user
      - im_write_user
      - im_write_organization
      - im_read_organization
      - im_read_role
      - im_write_role
