version: "3.3"

services:
  keycloak-it:
#    image: quay.io/keycloak/keycloak:17.0.0
    image: smartbcity/i2-keycloak:experimental
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: keycloak-postgres-it
      DB_SCHEMA: public
      DB_DATABASE: keycloack-it
      DB_USER: admin
      DB_PASSWORD: admin
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
      KEYCLOAK_HOSTNAME: localhost
#      KEYCLOAK_ADMIN:
#      KEYCLOAK_ADMIN_PASSWORD:
      PROXY_ADDRESS_FORWARDING: "true"
      JDBC_PARAMS: "ssl=false"
    ports:
      - 8080:8080
    depends_on:
      - keycloak-postgres-it
#    command: start-dev

  keycloak-postgres-it:
    image: postgres
    environment:
      POSTGRES_DB: keycloack-it
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
