version: "3.3"

services:
  keycloak:
    image: smartbcity/i2-keycloak:experimental
    container_name: keycloak
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: keycloak-postgres
      DB_SCHEMA: public
      DB_DATABASE: keycloack
      DB_USER: admin
      DB_PASSWORD: admin
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
      KEYCLOAK_HOSTNAME: localhost
      PROXY_ADDRESS_FORWARDING: "true"
      JDBC_PARAMS: "ssl=false"
    ports:
      - 8080:8080
    depends_on:
      - keycloak-postgres

  keycloak-postgres:
    image: postgres
    container_name: keycloak-postgres
    environment:
      POSTGRES_DB: keycloack
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
