spring:
  main:
    web-application-type: none

i2:
  keycloak:
    auth-server-url: https://localhost:8080/auth
    realm: test
    client-id: sb-realm-manager-app
    client-secret: secretsecret
  json: file:/Users/teddy/workspace/i2/i2-app/config/test.json
