spring:
  main:
    web-application-type: none

i2:
  keycloak:
    serverUrl: http://keycloak-it:8080/auth
    realm: test
    clientId: i2-test-client
    client-Secret: secret
  config:
    maxRetries: 5
    retryDelayMillis: 10000
    json: file:./i2-app/config/test.json
