spring:
  main:
    web-application-type: none

i2:
  keycloak:
    serverUrl: http://keycloak-it:8080/auth
    realm: master
    username: root
    password: root
    clientId: admin-cli
  init:
    maxRetries: 5
    retryDelayMillis: 10000
    realm: test
    smtp:
      host: me-email
      port: 1025
      from: noreply@smartb.city
      ssl: false
      starttls: false
      auth: false
    adminClient:
      name: i2-test-client
      secret: secret
    baseRoles:
      - super_admin
      - im_read_user
      - im_write_user
      - im_write_organization
      - im_read_organization
      - im_read_role
      - im_write_role
      - im_write_my_organization
      - admin
      - user

#i2:
#  keycloak:
#    auth-server-url: http://localhost:8080/auth
#    realm: master
#    username: admin
#    password: admin
#    client-id: admin-cli
#  init:
#    maxRetries: 5
#    retryDelayMillis: 10000
#    realm: test
#    smtp:
#      host: me-email
#      port: 1025
#      from: noreply@smartb.city
#      ssl: false
#      starttls: false
#      auth: false
#    admin-client:
#      name: sb-realm-manager-app
#      secret: secretsecret
#    base-roles:
#      - super_admin
#      - im_read_user
#      - im_write_user
#      - im_write_organization
#      - im_read_organization
#      - im_read_role
#      - im_write_role
#      - im_write_my_organization
#      - admin
#      - user
