package i2.s2.organization.f2.model.insee

data class InseeLegalUnit(
    val etatAdministratifUniteLegale: String?,
    val statutDiffusionUniteLegale: String?,
    val dateCreationUniteLegale: String?,
    val categorieJuridiqueUniteLegale: String?,
    val denominationUniteLegale: String?,
    val sigleUniteLegale: String?,
    val denominationUsuelle1UniteLegale: String?,
    val denominationUsuelle2UniteLegale: String?,
    val denominationUsuelle3UniteLegale: String?,
    val sexeUniteLegale: String?,
    val nomUniteLegale: String?,
    val nomUsageUniteLegale: String?,
    val prenom1UniteLegale: String?,
    val prenom2UniteLegale: String?,
    val prenom3UniteLegale: String?,
    val prenom4UniteLegale: String?,
    val prenomUsuelUniteLegale: String?,
    val pseudonymeUniteLegale: String?,
    val activitePrincipaleUniteLegale: String?,
    val nomenclatureActivitePrincipaleUniteLegale: String?,
    val identifiantAssociationUniteLegale: String?,
    val economieSocialeSolidaireUniteLegale: String?,
    val caractereEmployeurUniteLegale: String?,
    val trancheEffectifsUniteLegale: String?,
    val anneeEffectifsUniteLegale: String?,
    val nicSiegeUniteLegale: String?,
    val dateDernierTraitementUniteLegale: String?,
    val categorieEntreprise: String?,
    val anneeCategorieEntreprise: String?
)
