spring:
  main:
    web-application-type: none

i2:
  keycloak:
    auth-server-url: http://localhost:8080/auth
    realm: boislocal-local
    client-id: i2-admin
    client-secret: secret
#  json: file:/Users/teddy/workspace/i2/i2-config/api-config/test.json
  config:
    web-client:
      client-id: boislocal-web
      web-url: https://application.com
      localhost-url: http://localhost:3000
    app-client:
      client-id: boislocal-api
      roles:
        - super_admin
#    users:
#      -
#        username: user1
#        email: user1@mail.com
#        password: user1user
#        firstname: user1
#        lastname: user1
#        role: admin
#    roles:
#      - admin
#      - role1
#      - role2
#      - role3
#    role-composites:
#      admin: ["role1"]
#      role1: ["role2", "role3"]
