server:
  port: 8083

i2:
  keycloak:
    auth-server-url: http://localhost:8080/auth
    realm: test
    client-id: i2-api
    client-secret: c54915d6-3498-4c8f-8143-7858fb72ef6f
#  json: file:/Users/teddy/workspace/i2/i2-config/api-config/test.json
  config:
    web-client:
      client-id: plateform-web
      web-url: https://application.com
      localhost-url: http://localhost:3000
    app-client:
      client-id: plateform-app
#    users:
#      -
#        username: user1
#        email: user1@mail.com
#        password: user1user
#        firstname: user1
#        lastname: user1
#        role: admin
#    roles:
#      - admin
#      - role1
#      - role2
#      - role3
#    role-composites:
#      admin: ["role1"]
#      role1: ["role2", "role3"]
