version: "3.3"

services:
  i2-init:
    image: smartbcity/i2-init
    network_mode: host
    environment:
      - i2_keycloak_serverUrl=http://localhost:8080/auth
      - i2_keycloak_username=admin
      - i2_keycloak_password=admin
      - i2_init_realm_name=test
      - i2_init_adminUser_username=admin
      - i2_init_adminUser_email=admin@admin.com
      - i2_init_adminUser_firstname=admin
      - i2_init_adminUser_lastname=admin
